(function(){
  'use strict';
  const $=id=>document.getElementById(id),fmt=n=>n===null?'—':new Intl.NumberFormat('fr-FR',{maximumFractionDigits:0}).format(n),signed=n=>n===null?'—':(n>=0?'+':'−')+fmt(Math.abs(n));
  window.BalanceVisual={render({day,intakeTarget,expense,sessions,resting,state,completed,projection}){
    const B=window.EquilibreBalance,a=B.activities(day,sessions,resting,state),p=B.progress(day.intake,intakeTarget,a.kcal,expense),e=B.expenditure(day,a,projection);
    $('balance-ring-progress').setAttribute('stroke-dasharray',`${p.ring*100} 100`);
    $('balance-visual').classList.toggle('over-budget',p.remaining!==null&&p.remaining<0);
    $('balance-ring-percent').textContent=p.ratio===null?'—':fmt(p.ratio*100)+' %';
    $('balance-ring-label').textContent='de l’objectif';
    $('balance-food-values').textContent=`${fmt(day.intake)} / ${fmt(intakeTarget)} kcal`;
    $('balance-ring').setAttribute('aria-label',`Apports : ${fmt(day.intake)} kcal ; objectif alimentaire : ${fmt(intakeTarget)} kcal.`);
    $('balance-food-status').textContent=p.remaining===null?'Repas ou objectif à renseigner':p.remaining>0?`${fmt(p.remaining)} kcal avant l’objectif`:p.remaining<0?`${fmt(-p.remaining)} kcal au-dessus de l’objectif`:'Objectif alimentaire atteint';
    $('balance-activity-title').textContent='Activité retenue';
    $('balance-active-value').textContent=(a.estimated&&a.kcal!==null?'≈ ':'')+fmt(a.kcal);
    $('balance-active-unit').textContent=day.routine&&day.maintenance==null?'kcal ajoutées':a.unclassified?'kcal de séances':'kcal actives';
    const scale=Math.max(a.kcal??0,e.included??0,1),hasEnvelope=e.included!==null,baseMode=e.base!==null;
    $('balance-active-bar').style.width=(hasEnvelope?Math.min(a.kcal??0,e.included)/scale*100:(p.activityRatio??0)*100)+'%';
    $('balance-extra-bar').style.width=(hasEnvelope?(e.excess??0)/scale*100:0)+'%';
    $('balance-active-track').classList.toggle('no-value',a.kcal===null);
    $('balance-active-share').textContent=hasEnvelope?`${fmt(e.included)} kcal supposées incluses · ${e.excess===null?'supplément inconnu':signed(e.excess)+' kcal en plus'}`:p.inconsistent?'Total de dépense à vérifier':p.activityRatio===null?'Part dans la dépense : à compléter':`≈ ${fmt(p.activityRatio*100)} % de la dépense retenue`;
    $('balance-active-detail').textContent=a.source==='none'?'En attente de données d’activité':a.source==='manual'?'Activités réalisées et marche renseignées':`${a.count} séance(s) retenue(s)${a.excludedCount?' · '+a.excludedCount+' plage Google Fit non ajoutée':''}${a.missing?' · '+a.missing+' sans calories':''}`;
    $('balance-expense-breakdown').hidden=e.reference===null;
    $('balance-reference-label').textContent=baseMode?'Base hors sport estimée':'Maintien habituel';
    $('balance-maintenance').textContent=fmt(e.reference)+' kcal';
    $('balance-included-row').hidden=baseMode;
    $('balance-included').textContent=e.included===null?'À renseigner':fmt(e.included)+' kcal';
    $('balance-envelope-note').hidden=baseMode?e.method!=='base':e.method!=='activity';
    $('balance-envelope-note').textContent=baseMode?(a.kcal===null?'Base seule provisoire : activité encore inconnue. Les séances reçues ou réalisées s’ajouteront sans seuil.':'La base comprend le repos, la digestion et les mouvements ordinaires. Les activités supplémentaires retenues s’ajoutent sans seuil.'):'Activité incluse : hypothèse à calibrer avec le maintien et les tendances de poids. Le maintien reste inchangé sous ce seuil. Ce repère est distinct du déficit cible.';
    if(baseMode&&day.routine){$('balance-activity-title').textContent='Supplément net d’activité';$('balance-active-detail').textContent=`${a.count} activité(s) retenue(s), dont ${a.walkCount} marche(s) hors séance`;if(a.kcal!==null)$('balance-envelope-note').textContent=`${fmt(a.rawKcal)} kcal retenues − ${fmt(a.rawKcal-a.kcal)} kcal déjà comprises dans la journée habituelle = +${fmt(a.kcal)} kcal ajoutées.`;}
    $('balance-adjustment-label').textContent=['manual','projected','complete'].includes(e.method)?'Ajustement du total':baseMode?'Activités supplémentaires':'Supplément d’activité';
    const approximate=e.method==='base'||e.method==='activity'&&e.provisional?'≈ ':'';
    $('balance-adjustment').textContent=e.method==='base'&&e.adjustment===null?'À compléter':(['base','activity'].includes(e.method)&&(a.estimated||a.unclassified)?'≈ ':'')+signed(e.adjustment)+' kcal';
    $('balance-expense').textContent=approximate+fmt(e.expense)+' kcal';
    $('balance-deficit-row').hidden=!baseMode;$('balance-budget-row').hidden=!baseMode;
    $('balance-deficit').textContent=day.target==null?'À renseigner':'−'+fmt(day.target)+' kcal';
    $('balance-budget').textContent=fmt(intakeTarget)+' kcal';
    $('balance-expense-equation').textContent=e.method==='base'?(a.kcal===null?`Dépense estimée pour l’instant : ${fmt(e.base)} kcal hors sport.`:`${fmt(e.base)} + ${fmt(a.kcal)} = ${fmt(e.expense)} kcal de dépense.`)+(day.target==null?'':day.target>e.expense?' Déficit cible supérieur à la dépense : objectif ramené à 0 kcal.':` Objectif alimentaire : ${fmt(e.expense)} − ${fmt(day.target)} = ${fmt(intakeTarget)} kcal.`):e.method==='activity'?(e.excess===null?'Maintien conservé en attendant les calories d’activité.':`${fmt(e.maintenance)} + max(0, ${fmt(e.activity)} − ${fmt(e.included)}) = ${fmt(e.expense)} kcal.`):['manual','projected','complete'].includes(e.method)?'Le total quotidien remplace la référence et toutes les activités. Aucun supplément n’est ajouté à ce total.':'Maintien fixe. Le mode ajusté et l’activité incluse se règlent dans Compte.';
    const notes=[];
    if(completed!==null&&completed<4)notes.push(`${completed}/4 repas renseignés : bilan provisoire.`);
    if(a.missing)notes.push('Calories d’activité incomplètes.');
    if(baseMode&&day.routine&&!a.walkingAvailable)notes.push('Marches hors séances : en attente des données par minute de la nouvelle passerelle.');
    if(a.coarseMinutes)notes.push('Certains pas sont trop agrégés pour reconnaître une marche.');
    if(a.uncorrected)notes.push('Part habituelle non déduite de certaines saisies : durée, poids ou métabolisme manquants.');
    if(a.unclassified)notes.push('Urevo : nature des calories à confirmer ; supplément estimé provisoire.');
    if(a.restAdjusted)notes.push('≈ : repos retiré du total de séance pour les autres sources.');
    if(a.overlap)notes.push('≈ : créneaux qui se chevauchent comptés une fois.');
    if(a.excludedCount)notes.push('Google Fit : plage englobant une séance d’une autre source, calories non ajoutées faute de détail hors chevauchement.');
    if(a.manualCount)notes.push(`${a.manualCount} saisie(s) manuelle(s) à part pour éviter les copies.`);
    if(baseMode&&day.activities.some(s=>s.state==='planned'))notes.push('Séances prévues : ajoutées au budget une fois réalisées.');
    $('balance-visual-note').textContent=notes.join(' ');$('balance-visual-note').hidden=!notes.length;
    $('balance-counting-note').textContent=e.method==='base'?'Base hors sport + activités retenues − déficit cible = objectif alimentaire du jour.':e.method==='activity'?'Le maintien comprend déjà l’activité habituelle. Seul son dépassement augmente la dépense.':'Les séances sont comptées une seule fois selon la méthode du profil.';
    return a;
  }};
})();
